package:
  name: udnn
  version: 0.3

source:
  url: https://files.pythonhosted.org/packages/d6/c5/4f1a05083cdf252a1bef176c3873798bc4a295a0d709a3fcfb2d1f9682b4/udnn-0.0.3.tar.gz
  sha256: e92f24704b70b0fbcd5389a7af30f743850a8855bf9ef6f4dba7d2757dd2e8ae

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - python >=3.6.4
    - pip
    - setuptools
  run:
    - python >=3.6.4
    - pytorch >=0.4.0
    - numpy
    - h5py
    - pillow

test:
  imports:
    - udnn

about:
  home: https://github.com/DimitriosBellos/UDNN
  license: Apache 2.0
  summary: A Convolutional Neural Network for fast upscaling of low-resolution sinograms in x-ray CT time-series

extra:
  recipe-maintainers:
    - DimitriosBellos
